import Config

# Configure your database
config :gpt_talkerbot, GptTalkerbot.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "gpt_talkerbot_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.
config :gpt_talkerbot, GptTalkerbotWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "H6N96Uw7KqSbsECPoS95okoPQ17P3jebGI5T7lWNjrCATsbsEHsunlpLcoaMgLP+",
  watchers: [
    # Start the esbuild watcher by calling Esbuild.install_and_run(:default, args)
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :ex_aws,
  access_key_id: [{:awscli, "default", 30}, :instance_role],
  secret_access_key: [{:awscli, "default", 30}, :instance_role],
  region: "us-east-2"

# RuntimeEnvs reads /gpt_talkerbot/prod/* when SSM is enabled. In development
# that can make the app validate the production webhook secret while dev_up.sh
# registered the local webhook without one.
config :gpt_talkerbot, :ssm_enabled, false

if File.exists?("config/dev.secret.exs") do
  import_config "dev.secret.exs"
end

# Overrides usados pelo scripts/dev_up.sh: precisam vir depois do
# dev.secret.exs para vencer os valores estáticos de lá
if server_host = System.get_env("SERVER_HOST") do
  config :gpt_talkerbot, :server_host, server_host
end

if webhook_secret = System.get_env("TELEGRAM_WEBHOOK_SECRET") do
  config :gpt_talkerbot, :telegram_webhook_secret, webhook_secret
end
